# Define the number of VMs to create
NUM_VMS = 3

Vagrant.configure("2") do |config|
  (1..NUM_VMS).each do |i|
    config.vm.define "vm#{i}" do |vm|
      vm.vm.box = "generic/rocky8"
      vm.vm.hostname = "vm#{i}"

      # Assign IP addresses dynamically based on the VM number
      vm.vm.network "private_network", ip: "192.168.56.#{100+i}"

      # VM provider-specific configuration
      vm.vm.provider "virtualbox" do |v|
        v.name = "vm#{i}"
        v.cpus = 2
        v.memory = 1024
      end
    end
  end
end
