- name: Create EC2 instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_secrets.yml
  tasks:
    - name: Launch instance
      ec2:
        key_name: ansible-demo
        instance_type: t2.micro
        image: ami-0d940f23d527c3ab1
        region: eu-west-1
        group: webServerSg
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        vpc_subnet_id: subnet-0af7f59cadc67246e
        wait: yes
        count: 1
      register: ec2
