Vagrant.configure("2") do |config|
  
    config.vm.define "apache" do |apache|
      apache.vm.box = "generic/ubuntu2204"
      apache.vm.hostname = "apache"
      
      apache.vm.provider "virtualbox" do |vb|
        vb.name = "apache-vm"
        vb.memory = "1024"
        vb.cpus = 2
      end
  
      apache.vm.network "private_network", ip: "192.168.56.150"
    end
  end
