---
- name: Tags example
  hosts: webservers
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags: install

    - name: Start Apache service
      service:
        name: apache2
        state: started
      tags: start
