Vagrant.configure("2") do |config|
    config.vm.synced_folder "./examples", "/home/vagrant/examples"
    config.vm.define "ansible" do |ansible|
      ansible.vm.box = "generic/ubuntu2204"
      ansible.vm.hostname = "ansible"
      
      ansible.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-vm"
        vb.memory = "2048"
        vb.cpus = 2
      end
  
      ansible.vm.network "private_network", ip: "192.168.56.112"
    end
  end
